# 1.25.5-alpine3.23 (linux/amd64)
FROM golang:1.25.6-alpine3.23@sha256:d9b2e14101f27ec8d09674cd01186798d227bb0daec90e032aeb1cd22ac0f029 AS builder

RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

RUN apk add --no-cache curl wget gcc make bash git musl-dev libc6-compat gettext

WORKDIR /go/github.com/thought-machine/prometheus-cardinality-exporter

COPY . .

RUN go build ./...

RUN go test ./... -race

# So the binary is where we expect it
# env var and flags ensure a static binary
RUN CGO_ENABLED=0 go build -ldflags="-extldflags=-static" .

# alpine:3.23 (linux/amd64)
FROM alpine@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

EXPOSE 9090

COPY --from=builder /go/github.com/thought-machine/prometheus-cardinality-exporter/prometheus-cardinality-exporter /home/app/prometheus-cardinality-exporter

# Max user
RUN addgroup -g 255999 -S app && \
    adduser -u 255999 -S app -G app

RUN chmod +x /home/app/prometheus-cardinality-exporter

USER app

ENTRYPOINT ["/home/app/prometheus-cardinality-exporter"]
